name: CI/CD with Training and Deployment

on:
  push:
    branches:
      - main

jobs:
  train_and_deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        pip install -r requirements.txt

    - name: Train the model
      run: |
        python train.py
        mv data/churn_model.pkl data/  # Déplacer le modèle dans un dossier accessible

    - name: Build Docker image for Elastic Beanstalk
      run: |
        docker build -t churn-app .

    - name: Install AWS Elastic Beanstalk CLI
      run: |
        sudo apt-get update
        sudo apt-get install -y python3-pip
        pip3 install awsebcli --upgrade --user
        export PATH=$PATH:$HOME/.local/bin

    - name: Deploy to Elastic Beanstalk
      run: |
        eb init -p docker churn-app --region us-east-1
        eb deploy churn-env
