name: CI/CD with Model Versioning

on:
  push:
    branches:
      - main

jobs:
  train_and_deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        pip install -r requirements.txt

    - name: Train the model
      run: |
        python train.py

    - name: Save trained model to GitHub
      run: |
        git config user.name "GitHub Actions"
        git config user.email "actions@github.com"
        git add models/
        git commit -m "Add new model version [skip ci]"
        git push origin main

    - name: Install AWS Elastic Beanstalk CLI
      run: |
        sudo apt-get update
        sudo apt-get install -y python3-pip
        pip3 install awsebcli --upgrade --user
        export PATH=$PATH:$HOME/.local/bin

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v3
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Deploy to Elastic Beanstalk
      run: |
        eb deploy churn-env
